[mypy]
python_version = 3.10
ignore_missing_imports = True
check_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = False
exclude = (\.venv|database|face_data|reports)
